import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import NextTopLoader from 'nextjs-toploader';

import Navbar from '@/components/Navbar';
import { Toaster } from 'react-hot-toast';

import { createClient } from '@/utils/supabase/server';

import { UserProvider } from '@/context/UserProvider';
import { User } from '@supabase/supabase-js';
import { ThemeProvider } from '@/components/theme-provider';
import { QueryProvider } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader color="#2299DD" height={3} showSpinner={false} />{' '}
          <UserProvider initilUser={user as User}>
            <Navbar></Navbar>
            <QueryProvider>{children}</QueryProvider>
          </UserProvider>
          <Toaster
            position="top-right"
            reverseOrder={false}
            toastOptions={{
              // Default options
              duration: 3000,
              // Success
              position: 'top-center',

              success: {
                duration: 3000,
                iconTheme: {
                  primary: 'green',
                  secondary: 'white',
                },
              },
              // Error
              error: {
                duration: 4000,
                iconTheme: {
                  primary: 'red',
                  secondary: 'white',
                },
              },
            }}
          />
        </ThemeProvider>
      </body>
    </html>
  );
}
