import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import Navbar from '@/components/Navbar';
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Navbar></Navbar>
                {children}
                <Toaster
                    position="top-right"
                    reverseOrder={false}
                    toastOptions={{
                        // Default options
                        duration: 3000,
                        // Success
                        position: 'top-center',
                        
                        success: {
                            duration: 3000,
                            iconTheme: {
                                primary: 'green',
                                secondary: 'white',
                            },
                        },
                        // Error
                        error: {
                            duration: 4000,
                            iconTheme: {
                                primary: 'red',
                                secondary: 'white',
                            },
                        },
                    }}
                />
            </body>
        </html>
    );
}
