type CountryInfo = {
  emoji: string;
  fullName: string;
};

export function getCountryInfo(countryCode: string): CountryInfo | null {
  const countries: Record<string, CountryInfo> = {
    AF: { emoji: '🇦🇫', fullName: 'Afghanistan' },
    AL: { emoji: '🇦🇱', fullName: 'Albania' },
    DZ: { emoji: '🇩🇿', fullName: 'Algeria' },
    AD: { emoji: '🇦🇩', fullName: 'Andorra' },
    AO: { emoji: '🇦🇴', fullName: 'Angola' },
    AR: { emoji: '🇦🇷', fullName: 'Argentina' },
    AM: { emoji: '🇦🇲', fullName: 'Armenia' },
    AU: { emoji: '🇦🇺', fullName: 'Australia' },
    AT: { emoji: '🇦🇹', fullName: 'Austria' },
    AZ: { emoji: '🇦🇿', fullName: 'Azerbaijan' },
    BS: { emoji: '🇧🇸', fullName: 'Bahamas' },
    BH: { emoji: '🇧🇭', fullName: 'Bahrain' },
    BD: { emoji: '🇧🇩', fullName: 'Bangladesh' },
    BB: { emoji: '🇧🇧', fullName: 'Barbados' },
    BY: { emoji: '🇧🇾', fullName: 'Belarus' },
    BE: { emoji: '🇧🇪', fullName: 'Belgium' },
    BZ: { emoji: '🇧🇿', fullName: 'Belize' },
    BJ: { emoji: '🇧🇯', fullName: 'Benin' },
    BT: { emoji: '🇧🇹', fullName: 'Bhutan' },
    BO: { emoji: '🇧🇴', fullName: 'Bolivia' },
    BA: { emoji: '🇧🇦', fullName: 'Bosnia and Herzegovina' },
    BW: { emoji: '🇧🇼', fullName: 'Botswana' },
    BR: { emoji: '🇧🇷', fullName: 'Brazil' },
    BN: { emoji: '🇧🇳', fullName: 'Brunei' },
    BG: { emoji: '🇧🇬', fullName: 'Bulgaria' },
    BF: { emoji: '🇧🇫', fullName: 'Burkina Faso' },
    BI: { emoji: '🇧🇮', fullName: 'Burundi' },
    KH: { emoji: '🇰🇭', fullName: 'Cambodia' },
    CM: { emoji: '🇨🇲', fullName: 'Cameroon' },
    CA: { emoji: '🇨🇦', fullName: 'Canada' },
    CV: { emoji: '🇨🇻', fullName: 'Cape Verde' },
    CF: { emoji: '🇨🇫', fullName: 'Central African Republic' },
    TD: { emoji: '🇹🇩', fullName: 'Chad' },
    CL: { emoji: '🇨🇱', fullName: 'Chile' },
    CN: { emoji: '🇨🇳', fullName: 'China' },
    CO: { emoji: '🇨🇴', fullName: 'Colombia' },
    KM: { emoji: '🇰🇲', fullName: 'Comoros' },
    CG: { emoji: '🇨🇬', fullName: 'Congo' },
    CR: { emoji: '🇨🇷', fullName: 'Costa Rica' },
    HR: { emoji: '🇭🇷', fullName: 'Croatia' },
    CU: { emoji: '🇨🇺', fullName: 'Cuba' },
    CY: { emoji: '🇨🇾', fullName: 'Cyprus' },
    CZ: { emoji: '🇨🇿', fullName: 'Czech Republic' },
    DK: { emoji: '🇩🇰', fullName: 'Denmark' },
    DJ: { emoji: '🇩🇯', fullName: 'Djibouti' },
    DM: { emoji: '🇩🇲', fullName: 'Dominica' },
    DO: { emoji: '🇩🇴', fullName: 'Dominican Republic' },
    EC: { emoji: '🇪🇨', fullName: 'Ecuador' },
    EG: { emoji: '🇪🇬', fullName: 'Egypt' },
    SV: { emoji: '🇸🇻', fullName: 'El Salvador' },
    GQ: { emoji: '🇬🇶', fullName: 'Equatorial Guinea' },
    ER: { emoji: '🇪🇷', fullName: 'Eritrea' },
    EE: { emoji: '🇪🇪', fullName: 'Estonia' },
    ET: { emoji: '🇪🇹', fullName: 'Ethiopia' },
    FJ: { emoji: '🇫🇯', fullName: 'Fiji' },
    FI: { emoji: '🇫🇮', fullName: 'Finland' },
    FR: { emoji: '🇫🇷', fullName: 'France' },
    GA: { emoji: '🇬🇦', fullName: 'Gabon' },
    GM: { emoji: '🇬🇲', fullName: 'Gambia' },
    GE: { emoji: '🇬🇪', fullName: 'Georgia' },
    DE: { emoji: '🇩🇪', fullName: 'Germany' },
    GH: { emoji: '🇬🇭', fullName: 'Ghana' },
    GR: { emoji: '🇬🇷', fullName: 'Greece' },
    GD: { emoji: '🇬🇩', fullName: 'Grenada' },
    GT: { emoji: '🇬🇹', fullName: 'Guatemala' },
    GN: { emoji: '🇬🇳', fullName: 'Guinea' },
    GW: { emoji: '🇬🇼', fullName: 'Guinea-Bissau' },
    GY: { emoji: '🇬🇾', fullName: 'Guyana' },
    HT: { emoji: '🇭🇹', fullName: 'Haiti' },
    HN: { emoji: '🇭🇳', fullName: 'Honduras' },
    HU: { emoji: '🇭🇺', fullName: 'Hungary' },
    IS: { emoji: '🇮🇸', fullName: 'Iceland' },
    IN: { emoji: '🇮🇳', fullName: 'India' },
    ID: { emoji: '🇮🇩', fullName: 'Indonesia' },
    IR: { emoji: '🇮🇷', fullName: 'Iran' },
    IQ: { emoji: '🇮🇶', fullName: 'Iraq' },
    IE: { emoji: '🇮🇪', fullName: 'Ireland' },
    IL: { emoji: '🇮🇱', fullName: 'Israel' },
    IT: { emoji: '🇮🇹', fullName: 'Italy' },
    JM: { emoji: '🇯🇲', fullName: 'Jamaica' },
    JP: { emoji: '🇯🇵', fullName: 'Japan' },
    JO: { emoji: '🇯🇴', fullName: 'Jordan' },
    KZ: { emoji: '🇰🇿', fullName: 'Kazakhstan' },
    KE: { emoji: '🇰🇪', fullName: 'Kenya' },
    KI: { emoji: '🇰🇮', fullName: 'Kiribati' },
    KP: { emoji: '🇰🇵', fullName: 'North Korea' },
    KR: { emoji: '🇰🇷', fullName: 'South Korea' },
    KW: { emoji: '🇰🇼', fullName: 'Kuwait' },
    KG: { emoji: '🇰🇬', fullName: 'Kyrgyzstan' },
    LA: { emoji: '🇱🇦', fullName: 'Laos' },
    LV: { emoji: '🇱🇻', fullName: 'Latvia' },
    LB: { emoji: '🇱🇧', fullName: 'Lebanon' },
    LS: { emoji: '🇱🇸', fullName: 'Lesotho' },
    LR: { emoji: '🇱🇷', fullName: 'Liberia' },
    LY: { emoji: '🇱🇾', fullName: 'Libya' },
    LI: { emoji: '🇱🇮', fullName: 'Liechtenstein' },
    LT: { emoji: '🇱🇹', fullName: 'Lithuania' },
    LU: { emoji: '🇱🇺', fullName: 'Luxembourg' },
    MG: { emoji: '🇲🇬', fullName: 'Madagascar' },
    MW: { emoji: '🇲🇼', fullName: 'Malawi' },
    MY: { emoji: '🇲🇾', fullName: 'Malaysia' },
    MV: { emoji: '🇲🇻', fullName: 'Maldives' },
    ML: { emoji: '🇲🇱', fullName: 'Mali' },
    MT: { emoji: '🇲🇹', fullName: 'Malta' },
    MH: { emoji: '🇲🇭', fullName: 'Marshall Islands' },
    MR: { emoji: '🇲🇷', fullName: 'Mauritania' },
    MU: { emoji: '🇲🇺', fullName: 'Mauritius' },
    MX: { emoji: '🇲🇽', fullName: 'Mexico' },
    FM: { emoji: '🇫🇲', fullName: 'Micronesia' },
    MD: { emoji: '🇲🇩', fullName: 'Moldova' },
    MC: { emoji: '🇲🇨', fullName: 'Monaco' },
    MN: { emoji: '🇲🇳', fullName: 'Mongolia' },
    ME: { emoji: '🇲🇪', fullName: 'Montenegro' },
    MA: { emoji: '🇲🇦', fullName: 'Morocco' },
    MZ: { emoji: '🇲🇿', fullName: 'Mozambique' },
    MM: { emoji: '🇲🇲', fullName: 'Myanmar' },
    NA: { emoji: '🇳🇦', fullName: 'Namibia' },
    NR: { emoji: '🇳🇷', fullName: 'Nauru' },
    NP: { emoji: '🇳🇵', fullName: 'Nepal' },
    NL: { emoji: '🇳🇱', fullName: 'Netherlands' },
    NZ: { emoji: '🇳🇿', fullName: 'New Zealand' },
    NI: { emoji: '🇳🇮', fullName: 'Nicaragua' },
    NE: { emoji: '🇳🇪', fullName: 'Niger' },
    NG: { emoji: '🇳🇬', fullName: 'Nigeria' },
    NO: { emoji: '🇳🇴', fullName: 'Norway' },
    OM: { emoji: '🇴🇲', fullName: 'Oman' },
    PK: { emoji: '🇵🇰', fullName: 'Pakistan' },
    PW: { emoji: '🇵🇼', fullName: 'Palau' },
    PS: { emoji: '🇵🇸', fullName: 'Palestine' },
    PA: { emoji: '🇵🇦', fullName: 'Panama' },
    PG: { emoji: '🇵🇬', fullName: 'Papua New Guinea' },
    PY: { emoji: '🇵🇾', fullName: 'Paraguay' },
    PE: { emoji: '🇵🇪', fullName: 'Peru' },
    PH: { emoji: '🇵🇭', fullName: 'Philippines' },
    PL: { emoji: '🇵🇱', fullName: 'Poland' },
    PT: { emoji: '🇵🇹', fullName: 'Portugal' },
    QA: { emoji: '🇶🇦', fullName: 'Qatar' },
    RO: { emoji: '🇷🇴', fullName: 'Romania' },
    RU: { emoji: '🇷🇺', fullName: 'Russia' },
    RW: { emoji: '🇷🇼', fullName: 'Rwanda' },
    KN: { emoji: '🇰🇳', fullName: 'Saint Kitts and Nevis' },
    LC: { emoji: '🇱🇨', fullName: 'Saint Lucia' },
    VC: { emoji: '🇻🇨', fullName: 'Saint Vincent and the Grenadines' },
    WS: { emoji: '🇼🇸', fullName: 'Samoa' },
    SM: { emoji: '🇸🇲', fullName: 'San Marino' },
    ST: { emoji: '🇸🇹', fullName: 'Sao Tome and Principe' },
    SA: { emoji: '🇸🇦', fullName: 'Saudi Arabia' },
    SN: { emoji: '🇸🇳', fullName: 'Senegal' },
    RS: { emoji: '🇷🇸', fullName: 'Serbia' },
    SC: { emoji: '🇸🇨', fullName: 'Seychelles' },
    SL: { emoji: '🇸🇱', fullName: 'Sierra Leone' },
    SG: { emoji: '🇸🇬', fullName: 'Singapore' },
    SK: { emoji: '🇸🇰', fullName: 'Slovakia' },
    SI: { emoji: '🇸🇮', fullName: 'Slovenia' },
    SB: { emoji: '🇸🇧', fullName: 'Solomon Islands' },
    SO: { emoji: '🇸🇴', fullName: 'Somalia' },
    ZA: { emoji: '🇿🇦', fullName: 'South Africa' },
    SS: { emoji: '🇸🇸', fullName: 'South Sudan' },
    ES: { emoji: '🇪🇸', fullName: 'Spain' },
    LK: { emoji: '🇱🇰', fullName: 'Sri Lanka' },
    SD: { emoji: '🇸🇩', fullName: 'Sudan' },
    SR: { emoji: '🇸🇷', fullName: 'Suriname' },
    SE: { emoji: '🇸🇪', fullName: 'Sweden' },
    CH: { emoji: '🇨🇭', fullName: 'Switzerland' },
    SY: { emoji: '🇸🇾', fullName: 'Syria' },
    TW: { emoji: '🇹🇼', fullName: 'Taiwan' },
    TJ: { emoji: '🇹🇯', fullName: 'Tajikistan' },
    TZ: { emoji: '🇹🇿', fullName: 'Tanzania' },
    TH: { emoji: '🇹🇭', fullName: 'Thailand' },
    TL: { emoji: '🇹🇱', fullName: 'Timor-Leste' },
    TG: { emoji: '🇹🇬', fullName: 'Togo' },
    TO: { emoji: '🇹🇴', fullName: 'Tonga' },
    TT: { emoji: '🇹🇹', fullName: 'Trinidad and Tobago' },
    TN: { emoji: '🇹🇳', fullName: 'Tunisia' },
    TR: { emoji: '🇹🇷', fullName: 'Turkey' },
    TM: { emoji: '🇹🇲', fullName: 'Turkmenistan' },
    TV: { emoji: '🇹🇻', fullName: 'Tuvalu' },
    UG: { emoji: '🇺🇬', fullName: 'Uganda' },
    UA: { emoji: '🇺🇦', fullName: 'Ukraine' },
    AE: { emoji: '🇦🇪', fullName: 'United Arab Emirates' },
    GB: { emoji: '🇬🇧', fullName: 'United Kingdom' },
    US: { emoji: '🇺🇸', fullName: 'United States' },
    UY: { emoji: '🇺🇾', fullName: 'Uruguay' },
    UZ: { emoji: '🇺🇿', fullName: 'Uzbekistan' },
    VU: { emoji: '🇻🇺', fullName: 'Vanuatu' },
    VA: { emoji: '🇻🇦', fullName: 'Vatican City' },
    VE: { emoji: '🇻🇪', fullName: 'Venezuela' },
    VN: { emoji: '🇻🇳', fullName: 'Vietnam' },
    YE: { emoji: '🇾🇪', fullName: 'Yemen' },
    ZM: { emoji: '🇿🇲', fullName: 'Zambia' },
    ZW: { emoji: '🇿🇼', fullName: 'Zimbabwe' },
  };

  const code = countryCode.toUpperCase();
  return countries[code] || null;
}

// Usage examples:
// getCountryInfo('US') // { emoji: '🇺🇸', fullName: 'United States' }
// getCountryInfo('MA') // { emoji: '🇲🇦', fullName: 'Morocco' }
// getCountryInfo('us') // { emoji: '🇺🇸', fullName: 'United States' } (case insensitive)
// getCountryInfo('XX') // null (invalid code)
